# Generated by Django 5.1.7 on 2025-04-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(
                blank=True,
                choices=[
                    ("P", "교수/강사"),
                    ("S", "학생"),
                    ("R", "연구원"),
                    ("E", "기타"),
                ],
                max_length=1,
                null=True,
                verbose_name="직업",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
