# Generated by Django 5.1.7 on 2025-04-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_job_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="old_cart",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="이메일"),
        ),
    ]
